development:
  adapter: postgresql
  encoding: unicode
  database: booyah_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: booyah_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: booyah_production
  pool: 5

cucumber:
  <<: *test